//! Auto-generated GitLab API client and types from OpenAPI spec via Progenitor.
//!
//! This module includes the code generated by `build.rs` from
//! `specs/gitlab-openapi3-trimmed.yaml`. It provides:
//!
//! - `Client` — typed HTTP client with methods for each API endpoint
//! - `types` — request/response types generated from OpenAPI schemas
//!
//! The generated `Client` wraps a `reqwest::Client` and provides typed methods
//! like `get_api_v4_user()`, `get_api_v4_groups_id_projects()`, etc.
//! `ResponseValue<T>` returned by these methods gives access to both the typed
//! body and response headers (for rate limit tracking, pagination, ETag caching).

include!(concat!(env!("OUT_DIR"), "/gitlab_generated.rs"));
