//! Auto-generated GitLab API types from OpenAPI spec via Progenitor.
//!
//! This module includes the code generated by `build.rs` from
//! `specs/gitlab-openapi3-trimmed.yaml`. It provides:
//!
//! - `types` — request/response types generated from OpenAPI schemas
//! - `Client` — typed HTTP client (retained for type generation, but not used
//!   directly for API calls)
//!
//! **Note:** The GitLab client (`super::client::GitLabClient`) now uses the
//! `HttpTransport` trait for all HTTP I/O rather than the generated `Client`.
//! The generated types in this module are still used by `super::types` for
//! `From` conversions (e.g., `ApiEntitiesProject` → `GitLabProject`).

include!(concat!(env!("OUT_DIR"), "/gitlab_generated.rs"));
