---
name: Setup Nix
description: Install Nix with Determinate Systems installer and Magic Nix Cache

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v21

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
      env:
        # Magic Nix Cache uses the GitHub API (and GHA cache) under the hood.
        # If it runs unauthenticated, it can quickly hit rate limits in CI.
        GITHUB_TOKEN: ${{ github.token }}
